### ISSUE TITLE
请问您用Dlib做预处理时，有遇到很多图片的人脸检测不出的情况吗

### ISSUE THREAD

**Issue by cyZhu98** [Open-Debin/Emotion-FAN#18]
i used dlib-python to preprocess the images obtained from videos by ffmpeg ,but failed to dectect face in many frames,how you handled this

**Comment by zyy9605** [comment]
我也遇到了相同的问题，很多人脸检测不出来。请问你找到解决方法了吗？

**Comment by Open-Debin** [comment]
> i used dlib-python to preprocess the images obtained from videos by ffmpeg ,but failed to dectect face in many frames,how you handled this

Hi, we ignore the faces that are failed to detected. Because, we think those faces are bad quality.
I think facial expression is harder than facial detection. If a face is failed to detected it will more hard for learning facial expression. The bad quality facial expression may hurt the network learning.

**Comment by Open-Debin** [comment]
> 我也遇到了相同的问题，很多人脸检测不出来。请问你找到解决方法了吗？

Hi, we ignore the faces that are failed to detected. Because, we think those faces are bad quality.
I think facial expression is harder than facial detection. If a face is failed to detected it might be more hard for learning facial expression. The bad quality facial expression may hurt the network learning.

**Comment by zyy9605** [comment]
> > 我也遇到了相同的问题，很多人脸检测不出来。请问你找到解决方法了吗？
> 
> Hi, we ignore the faces that are failed to detected. Because, we think those faces are bad quality.
> I think facial expression is harder than facial detection. If a face is failed to detected it might be more hard for learning facial expression. The bad quality facial expression may hurt the network learning.

Get it. Thank you!

**Comment by cyZhu98** [comment]
> > i used dlib-python to preprocess the images obtained from videos by ffmpeg ,but failed to dectect face in many frames,how you handled this
> 
> Hi, we ignore the faces that are failed to detected. Because, we think those faces are bad quality.
> I think facial expression is harder than facial detection. If a face is failed to detected it will more hard for learning facial expression. The bad quality facial expression may hurt the network learning.

Thank you for your reply

**Comment by Open-Debin** [comment]
@zyy9605 @cyZhu-upup 
Merry Christmas, I recently update the Emotion-FAN, new features include data process, environment install, CK+ code, Baseline code, and more detail instructions. Also, you can find the old version directory of Emotion-FAN in the README.md. I hope my new updates can help you greatly. Please see the Emotion-FAN for more details.
